### ISSUE TITLE
Question: Does this library support importing scss files within scss files?

### ISSUE THREAD

**Issue by davidfurlong** [DomainGroupOSS/sass-to-emotion#13]
I'm happy to submit a PR if we go this direction. 
I'm running into this bug when running this on our codebase and wondered if theres a way to ignore failed files or to modify it so it runs.

```
/Users/DVF/Downloads/sass-to-emotion-master/node_modules/postcss/lib/container.js:148
        throw e;
        ^

TypeError: Cannot read property 'userSelectNone' of null
    at /Users/DVF/Projects/deedmob/www/client/c/_inputs/DeedSelect/DeedSelect.scss:47:3
    at /Users/DVF/Downloads/sass-to-emotion-master/transform.js:333:18
    at /Users/DVF/Downloads/sass-to-emotion-master/node_modules/postcss/lib/container.js:314:16
    at /Users/DVF/Downloads/sass-to-emotion-master/node_modules/postcss/lib/container.js:139:18
    at Rule.each (/Users/DVF/Downloads/sass-to-emotion-master/node_modules/postcss/lib/container.js:105:16)
    at Rule.walk (/Users/DVF/Downloads/sass-to-emotion-master/node_modules/postcss/lib/container.js:135:17)
    at /Users/DVF/Downloads/sass-to-emotion-master/node_modules/postcss/lib/container.js:152:24
    at Root.each (/Users/DVF/Downloads/sass-to-emotion-master/node_modules/postcss/lib/container.js:105:16)
    at Root.walk (/Users/DVF/Downloads/sass-to-emotion-master/node_modules/postcss/lib/container.js:135:17)
    at Root.walkAtRules (/Users/DVF/Downloads/sass-to-emotion-master/node_modules/postcss/lib/container.js:312:17)
    at processRoot (/Users/DVF/Downloads/sass-to-emotion-master/transform.js:315:8) {
  postcssNode: AtRule {
    raws: { before: '\n  ', between: '', afterName: ' ' },
    type: 'atrule',
    name: 'include',
    parent: Rule {
      raws: [Object],
      type: 'rule',
      nodes: [Array],
      parent: [Root],
      source: [Object],
      selector: '.deedName',
      lastEach: 13,
      indexes: [Object]
    },
    source: { start: [Object], input: [Input], end: [Object] },
    params: 'user-select-none',
    lastEach: 12,
    indexes: {
      '1': 0,
      '2': 0,
      '3': 0,
      '4': 0,
      '5': 0,
      '6': 0,
      '7': 0,
      '8': 0,
      '9': 0,
      '10': 0,
      '11': 0,
      '12': 0
    },
    originalParams: 'user-select-none'
  }
}
```

```scss
// DeedSelect.scss
@import 'theme.scss';
@import '_variables.scss';

.deedSelect {
  display: flex;
  flex-direction: column;
}

.deeds {
  display: flex;
  flex-wrap: wrap;
  margin-left: -$s-spacing;
}

.deed,
.deeds {
  // Needed because it can be in a modal
  z-index: $zindex-modal;
}

.deed {
  display: flex;
  position: relative;
  text-align: center;
  width: 100px;
  height: 100px;
  padding-top: $s-spacing;
  padding-left: $s-spacing;

  &:hover .deleteButton {
    display: flex;
  }
}

.deedBox {
  justify-content: center;
  align-items: center;
  display: flex;
  background-color: $white10;
  width: 100px;
  height: 100px;
  overflow: auto;
}

.deedName {
  @include user-select-none;
  word-wrap: break-word;
  overflow: auto;
}

.deleteButton {
  display: none;
  position: absolute;
  top: $r-spacing;
  right: $s-spacing;
  cursor: pointer;
}
```
